### ISSUE TITLE
Animals Lifespan data not posting in the proper cell.

### ISSUE THREAD

**Issue by herrtodd33** [herrtodd33/southwestdata#5]
Animals Lifespan data not posting in the proper cells,
on the: http://southwestdata.info/admin/admin_system.php page

**Comment by d4rkd0s** [comment]
Found the bug!

https://github.com/herrtodd33/southwestdata/blob/3654828f57496dc4e231eb2f76d495578864fa51/admin/admin_system.php#L115-L124

Specifically, Line 118 you have `</tr>` which closes the row, this is why those cells are just gone, because the row is closed before you finish echoing out the `<td></td>` cells.

Line 118 should be changed from:
`echo "</tr>";`
to:
`echo "<td>";`

**Comment by d4rkd0s** [comment]
Specifically Line 118 you have `</tr>` which closes the row, this is why those cells are just gone, because the row is closed before you finish echoing out the `<td></td>` cells.

**Comment by herrtodd33** [comment]
I should have read you note earlier. But it was good that I found it on my own I guess.
